### ISSUE TITLE
 Option 'mode' is unknown. error

### ISSUE THREAD

**Issue by mattfox27** [nullpainter/sanchez#100]
Trying to do a stitch using windows and I get this error using the example script in wiki

`Sanchez reproject -s C:\Users\Matt\goes-share\*.jpg -o stitched.jpg --mode stitch -T 2024-02-18T03:50:20 -a`

**Comment by nullpainter** [comment]
Ooh good catch - I can't remember doing so, but I must have removed that, presumably because the mode is implicit when using `-T`. I've updated the doco. 

Does it work correctly without that arg?

**Comment by mattfox27** [comment]
I'll give it a try in the AM

**Comment by nullpainter** [comment]
How did this go?

**Comment by mattfox27** [comment]
Seems to be working
