### ISSUE TITLE
No output file format checks

### ISSUE THREAD

**Issue by nullpainter** [nullpainter/sanchez#2]
Sanchez always writes output files as JPEGs, regardless of the name of the output file. It should:

1. Look at output file extension
2. Validate that the extension is either PNG, JPG or JPEG
3. Choose the appropriate output writer

**Comment by nullpainter** [comment]
Fixed in v0.1.0.

**Comment by JimBobSquarePants** [comment]
ImageSharp will automatically choose the correct format to save if you use the [Image.`Save(string path)`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.ImageExtensions.html#SixLabors_ImageSharp_ImageExtensions_Save_SixLabors_ImageSharp_Image_System_String_) overload so you can do so without having to choose the format yourself.

https://github.com/nullpainter/sanchez/blob/7ce87d1c1fced1a8be27b182c638b96568ef67fc/Sanchez/Builders/CompositorBuilder.cs#L100

**Comment by nullpainter** [comment]
Thanks @JimBobSquarePants - I think it's fair to say that I know as much as I _need_ to know about ImageSharp (which right now is fairly little). 

Thanks for an awesome library. It's the core of Sanchez - everything else is just scaffolding and a silly name. ❤️

**Comment by nullpainter** [comment]
Removed hand-rolled image file format determination and validation. Fixed (again) in v0.1.0.
