### ISSUE TITLE
Linux version doesn't work

### ISSUE THREAD

**Issue by BX2ABT** [nullpainter/sanchez#22]
```
hans@G510:~/sanchez-v0.2.2-linux-x64$ ./Sanchez -s ./IMG_FD_018_IR105_20200804_030006.jpg -m ./Resources/Mask.jpg -u ./Resources/GK-2A/Underlay.jpg -o Output.jpg -t "#0096FA"

0 images composited
1 files ignored
```

Variations on this command line all resulted in the same: 0 images composited, 1 files ignored.
Used the latest x64 version from Github.

Could you please also give instructions on how to compile sanchez on Linux.

**Comment by nullpainter** [comment]
Thanks for reporting this - I can replicate. Logs are also missing, so I'll see if I can look at both of these today.

Regarding compilation, Sanchez is a .NET Core application. If you haven't built .NET Core on Linux before, you will need to install the SDK. General instructions are [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux). On Ubuntu, this will be:

```
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-3.1
```

Then in the Sanchez source folder, just run `dotnet run`. This will download third-party packages, build it and run the application.

Note that command-line arguments will need to be separated from the `dotnet` command with a `--`, as `dotnet` has its own arguments. 

e.g.:

```
dotnet run -- -u Resources\GK-2A\Underlay.jpg ...
```

**Comment by nullpainter** [comment]
Incidentally, on WSL2 at least, everything runs fine when running Sanchez like this.

**Comment by nullpainter** [comment]
I've also built it on WSL2 and things seem fine. Could you also try this from the source directory as an interim approach? The following command will create a native application in the `output` directory. This is the same approach as the Github publish workflow uses:

```
 dotnet publish  Sanchez/Sanchez.csproj -p:PublishSingleFile=true -p:PublishTrimmed=true -r linux-x64 -c Release -o output
```

**Comment by nullpainter** [comment]
Right, I've fixed the log creation issue which appears to have also fixed your issue. Are you able to grab v0.2.3 and let me know?

**Comment by BX2ABT** [comment]
Brilliant! v0.2.3 does indeed work, so problem fixed. Thanks for the fast response, that really made my day.

BTW, the syntax for batch conversion doesn't work. 

`./Sanchez -s "c:\images\Himawari8\**\*-IR*.jpg" -m Resources\Mask.jpg -u Resources\Himawari-8\Underlay-Hirez.jpg -o Output`

If you specify an output directory like -o Output, then the input directory should be similarly specified. This worked for me....

`./Sanchez -s ./Input -t #0070ba -m ./Resources/Mask.jpg -u ./Resources/GK-2A/Underlay.jpg -o ./Output`

Linux only here, so couldn't test this on Windows, Mac or WSL.

Again, brilliant work on this. I tried it manually using GIMP, but your process works much better. Hope you can do a write-up on what steps you have implemented to achieve this.

**Comment by nullpainter** [comment]
Oh, splendid! The example from the README was under Windows - I may make a note that slashes etc. need to be tweaked accordingly for non-Windows platforms.

I'm really happy that people are using Sanchez! It was really just applying in code what I had done in Photoshop, namely:

* Start with underlay image 
* Blend image with IR image using screen blend mode
* Optionally tweak brightness/saturation
* Optionally add overlay using normal blend mode
* Optionally add mask using multiply blend mode

If you're interested, I'm currently working on a new application which can be used in companion to Sanchez. The new application performs projection transformation of the full disc geostationary images into Mercator projection and will blend IR images from multiple satellites (GOES-16, GOES-17 etc.). Output will be similar to the [image here](https://www.reddit.com/r/amateursatellites/comments/i3wkkv/combined_satellite_imagery_from_goes_17/) with cropping.

**Comment by nullpainter** [comment]
Oh, I forgot! I'm also applying a (default blueish) tint to the IR image so it doesn't end up looking grey. And then, to avoid the bright clouds all looking blue, I'm blending the IR image with itself with a hard light. I think those two steps are the secret sauce! ;-)
