### ISSUE TITLE
sample image

### ISSUE THREAD

**Issue by zhzhixi** [nullpainter/sanchez#44]
This software is wonderful!
![Output5](https://user-images.githubusercontent.com/19346160/90383916-6070e280-e0b3-11ea-8139-441a7bbfc32e.jpg)

**Comment by nullpainter** [comment]
Thank you so much! Great image. I'll add it to the gallery ❤️

**Comment by nullpainter** [comment]
Finally added to the sample image gallery! Thanks again.
