### ISSUE TITLE
GOES 16 8.30.2020 this is Band 02 processed with Sanchez software, I then applied my custom LUT to the image.

### ISSUE THREAD

**Issue by creinemann** [nullpainter/sanchez#46]
![GOES16_FD_CH02_20200830T160020Z-fc](https://user-images.githubusercontent.com/47005123/91665081-c187b580-eab8-11ea-8141-67a5ef249ce9.jpg)

**Comment by nullpainter** [comment]
Beautiful, thanks!

**Comment by nullpainter** [comment]
(Your country and state boundary lines do show that something - most likely my underlay - is slightly out of whack though!)

**Comment by creinemann** [comment]
Yes, I saw that and if you look at the west coast of N America. because
it's slightly out of alignment, the mountains look like a bit of a double
exposure
Carl

**Comment by nullpainter** [comment]
Are you able to send me the IR image you used? Keen to see if the next version of Sanchez addresses this.

**Comment by creinemann** [comment]
![GOES16_FD_CH02_20200831T160020Z](https://user-images.githubusercontent.com/47005123/91758837-3d0b6480-eb96-11ea-87cd-dbfa69f3e27f.jpg)
Here's one from today.

**Comment by creinemann** [comment]
One solution on my end would be to eliminate the map overlay....

**Comment by nullpainter** [comment]
Would you look at that! 

![GOES16_FD_CH13_91758837-3d0b6480-eb96-11ea-87cd-dbfa69f3e27f-FC-1](https://user-images.githubusercontent.com/1732347/91763804-41815d00-ec2a-11ea-9bb1-9fe947e7d413.jpg)

**Comment by nullpainter** [comment]
There we go! Much better:

![GOES16_FD_CH13_91758837-3d0b6480-eb96-11ea-87cd-dbfa69f3e27f-FC-1](https://user-images.githubusercontent.com/1732347/91764411-5ca09c80-ec2b-11ea-8bd1-1b2968902a7a.jpg)

What channel are you using, btw? I'm using CH13 and the relay from GOES-17 looks quite different (and, IMO, better):

![GOES16_FD_CH13_20200830T035020Z-FC](https://user-images.githubusercontent.com/1732347/91764472-793cd480-ec2b-11ea-968f-e98bb6dbd600.jpg)

**Comment by creinemann** [comment]
For the one I sent,
![GOES16_FD_CH13_20200831T173020Z-fc](https://user-images.githubusercontent.com/47005123/91769218-91b5dc00-eba4-11ea-8061-63cddc845db9.jpg)
 I used Channel 2 Visible, Heres one with ch 13 and 15 Enhanced (I applied 15 separately after the Sanchez process).

**Comment by nullpainter** [comment]
Very nice. I'm not surprised the alignment is better in the new Sanchez, as the underlay is dynamically (and correctly!) reprojected based on the satellite longitude. The pre-rendered underlays in the current version were sized by eye.

**Comment by creinemann** [comment]
Just realized my Channel 15 layer is a bit off in size, My fault.
