### ISSUE TITLE
Inconsistent brightness on win x64

### ISSUE THREAD

**Issue by jiangyi1985** [nullpainter/sanchez#47]
On win x64 the brightness seem to be changing for different images.

original GK-2A:
![animated_org](https://user-images.githubusercontent.com/11713383/96028049-63a60600-0e8b-11eb-995f-a6051c201bd5.gif)

windows 10 x64:
C:\D\sanchez-v1.0.8-win-x64>Sanchez.exe -s 20201011 -o 20201011_colored
![animated](https://user-images.githubusercontent.com/11713383/96027347-55a3b580-0e8a-11eb-88ab-2edee339504a.gif)

linux raspberrypi 5.4.51
pi@raspberrypi:~ $ sanchez-v1.0.8-linux-arm/Sanchez -s xrit-rx/received/LRIT/20201011 -o xrit-rx/COLORED
![animated2](https://user-images.githubusercontent.com/11713383/96027556-9e5b6e80-0e8a-11eb-96c9-1a7a6da973e9.gif)

(gif created with ImageMagick7 windows version)

**Comment by nullpainter** [comment]
Thanks for reporting this, Ivan. This seems to be unique to GK-2A and my suspicion is that it's related to the different temperature of Australia over a 24 hour period, combined with auto level adjustment.

Try with the `-L` option to not perform automatic level adjustments.

**Comment by jiangyi1985** [comment]
> 
> 
> Thanks for reporting this, Ivan. This seems to be unique to GK-2A and my suspicion is that it's related to the different temperature of Australia over a 24 hour period, combined with auto level adjustment.
> 
> Try with the `-L` option to not perform automatic level adjustments.

`-L` works like magic. Thanks!
Btw, is it possible to change the brightness of the haze?

**Comment by nullpainter** [comment]
Sure, that's a reasonable request. I'll add it to be backlog. Thanks!
