### ISSUE TITLE
Use timestamp to determine if underlay (ándale?) should be cached

### ISSUE THREAD

**Issue by mlavespere** [nullpainter/sanchez#49]
I use xplanet to dynamically create a day/night underlay every 30 minutes. I have to change the name of the underlay file  each time or sanchez will use a cached copy. Can you refresh the cache if the timestamp on the underlay image has changed? 

![day_night_2020-10-16_09:40:01](https://user-images.githubusercontent.com/16197311/96266121-4a3cb100-0f94-11eb-8a9e-b529ac914b7f.jpg)

**Comment by nullpainter** [comment]
Ooh neat! Sure, that seems sensible. I'd love to see some of your results and maybe add one to the sample images page.

**Comment by mlavespere** [comment]
Sample image added. Thanks.

**Comment by nullpainter** [comment]
Fixed in v1.0.9 by looking at the last modified time. Thanks for reporting this! Please give it a go and let me know how you get on.
