### ISSUE TITLE
Would you consider compiling a FreeBSD version as well?

### ISSUE THREAD

**Issue by claudioguareschi** [nullpainter/sanchez#50]
Thanks for all the different Linux, OSX, WIndows versions of this great software.

Would it be possible to compile a FreeBSD 12 version as well?

Thanks

**Comment by nullpainter** [comment]
Thanks for the feedback. Unfortunately, I can only target compilation for the runtimes that dotnet supports. These are [listed here](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog). BSD isn't listed here, so unless the Linux version works you may need to build Sanchez from source.

Sorry about that!

M
