### ISSUE TITLE
Day and night images for creating underlay using Xplanet

### ISSUE THREAD

**Issue by mlavespere** [nullpainter/sanchez#52]
Day (earth.jpg)
![earth](https://user-images.githubusercontent.com/16197311/96572930-73628780-129b-11eb-9b35-691f9bc45a7f.jpg)

Night (night.jpg)
![night](https://user-images.githubusercontent.com/16197311/96572919-70679700-129b-11eb-9fa6-a199b9769154.jpg)

**Comment by nullpainter** [comment]
Thanks! I've added it to a new [underlays](https://github.com/nullpainter/sanchez/wiki/Underlays) page. Hope my interpretation of your instructions are correct.
