### ISSUE TITLE
Command to do 24 hour Stitch in a Specific Date

### ISSUE THREAD

**Issue by ZL1LAC** [nullpainter/sanchez#67]
Being able to get a Multiple satellite stitching with a specific date would be cool. So the following would auto generate 24 images within that date.

`./Sanchez reproject -s "M:\Satellite Images" --mode stitch -T 2021-01-26T00:50:20~2021-01-26-23:50:20 -a`

Or,

`./Sanchez reproject -s "M:\Satellite Images" --mode stitch -T 26-01-2021`

That would stitch the satellites together for the last 24 hours.  Just an idea.

**Comment by creinemann** [comment]
Doesn't this do this already with the -e argument? such as -T 2021-01-27T00:00:20 -e 2021-01-28T00:00:20 or whatever date/ time you want.

**Comment by ZL1LAC** [comment]
I just tried it with the argument you specified and its only doing one image unless I'm doing it wrong, the idea behind the command is to make 24 images 1 for each hour passed.

**Comment by nullpainter** [comment]
Thanks @creinemann - I had forgotten I had already built that! @ZL1LAC I thought you were after a start/end time? If you are only receiving one or two images per hour, I'm not sure why you would want 24 images as a result as most will be identical.

**Comment by ZL1LAC** [comment]
24 images one for each hour passed.  So far I have been doing it manually with the following command.

Sanchez reproject -s "M:\Satellite Images" -o S:\sanchez\out -a -T 2021-%1-%2T%3:%4:%5

```
.\stitch.bat 01 26 00 50 18
.\stitch.bat 01 26 01 50 18
.\stitch.bat 01 26 02 50 18
.\stitch.bat 01 26 03 50 18
.\stitch.bat 01 26 04 50 18
.\stitch.bat 01 26 05 50 18
.\stitch.bat 01 26 06 50 18
.\stitch.bat 01 26 07 50 18
.\stitch.bat 01 26 08 50 18
.\stitch.bat 01 26 09 50 18
.\stitch.bat 01 26 10 50 18
.\stitch.bat 01 26 11 50 18
.\stitch.bat 01 26 12 50 18
.\stitch.bat 01 26 13 50 18
.\stitch.bat 01 26 14 50 18
.\stitch.bat 01 26 15 50 18
.\stitch.bat 01 26 16 50 18
.\stitch.bat 01 26 17 50 18
.\stitch.bat 01 26 18 50 18
.\stitch.bat 01 26 19 50 18
.\stitch.bat 01 26 20 50 18
.\stitch.bat 01 26 21 50 18
.\stitch.bat 01 26 22 50 18
.\stitch.bat 01 26 23 50 18
```

The command to stitch 3 satellite together for the each hour that's pasted within that date.
