### ISSUE TITLE
Global Composite Using Xplanet to create the day/night layer, with IR Imagery from GOES 16-17,GK2A, Himawari-8, EWS-G1, ElektroL2

### ISSUE THREAD

**Issue by creinemann** [nullpainter/sanchez#69]
![GEORING_DayNight_02062021](https://user-images.githubusercontent.com/47005123/107128342-83ba6480-6882-11eb-85d0-8cbff1d2da1b.jpg)

**Comment by nullpainter** [comment]
Thanks! I added it and others to a new [showcase](https://github.com/nullpainter/sanchez/wiki/Showcase) page. Your work deserves its own page! Do let me know if anything isn't quite right.
