### ISSUE TITLE
Dynamically identify EWS-G1 horizontal offset

### ISSUE THREAD

**Issue by nullpainter** [nullpainter/sanchez#72]
Possibly use the median position of medium to high intensity pixels?

**Comment by ZbychuButItWasTaken** [comment]
That's one way to do it, but the offsets change every 12h, and from what I've seen it is a constant change.. Maybe it would be more reliable to just have the offset in px and time of the change in the config?

**Comment by creinemann** [comment]
According to NOAA, EWS is centered in their imagery by the McDias software that finds the center of the current images disc, then crops the image . The reported center point of the image shifts.

IMGLIST EWS/FD.-99 TIME=7 9                                                                                                    
Image file directory listing for:EWS/FD                                                                                        
 Pos Satellite/         Date       Time      Center   Band(s)                                                                  
     sensor                                 Lat  Lon                                                                            
 --- -------------  ------------  --------  ---- ---- ------------                                                              
  27  GOES-13       22 JAN 21022  08:45:00     0  -66 1-4,6                                                                    
  26  GOES-13       22 JAN 21022  08:15:00     0  -66 1-4,6                                                                    
  25  GOES-13       22 JAN 21022  07:45:00     0  -57 1-4,6                                                                    
  24  GOES-13       22 JAN 21022  07:15:00     0  -57 1-4,6                                                                    
 166  GOES-13       21 JAN 21021  08:45:00     0  -66 1-4,6                                                                    
 165  GOES-13       21 JAN 21021  08:15:00     0  -66 1-4,6                                                                    
 164  GOES-13       21 JAN 21021  07:45:00     0  -57 1-4,6                                                                    
 163  GOES-13       21 JAN 21021  07:15:00     0  -57 1-4,6                                                                    
 120  GOES-13       20 JAN 21020  08:45:00     0  -66 1-4,6                                                                    
 119  GOES-13       20 JAN 21020  08:15:00     0  -66 1-4,6                                                                    
 118  GOES-13       20 JAN 21020  07:45:00     0  -57 1-4,6                                                                    
 117  GOES-13       20 JAN 21020  07:15:00     0  -57 1-4,6                                                                    
  74  GOES-13       19 JAN 21019  08:45:00     0  -66 1-4,6                                                                    
  73  GOES-13       19 JAN 21019  08:15:00     0  -66 1-4,6                                                                    
  72  GOES-13       19 JAN 21019  07:45:00     0  -57 1-4,6                                                                    
  71  GOES-13       19 JAN 21019  07:15:00     0  -57 1-4,6                                                                    
IMGLIST: done                                                                                                                  
IMGLIST EWS/FD.-99 TIME=19 21                                                                                                  
Image file directory listing for:EWS/FD                                                                                        
 Pos Satellite/         Date       Time      Center   Band(s)                                                                  
     sensor                                 Lat  Lon                                                                            
 --- -------------  ------------  --------  ---- ---- ------------                                                              
   4  GOES-13       21 JAN 21021  20:45:00     0  -57 1-4,6                                                                    
   3  GOES-13       21 JAN 21021  20:15:00     0  -57 1-4,6                                                                    
   2  GOES-13       21 JAN 21021  19:45:00     0  -66 1-4,6                                                                    
 185  GOES-13       21 JAN 21021  19:15:00     0  -66 1-4,6                                                                    
 143  GOES-13       20 JAN 21020  20:45:00     0  -57 1-4,6                                                                    
 142  GOES-13       20 JAN 21020  20:15:00     0  -57 1-4,6                                                                    
 141  GOES-13       20 JAN 21020  19:45:00     0  -66 1-4,6                                                                    
 140  GOES-13       20 JAN 21020  19:15:00     0  -66 1-4,6                                                                    
  97  GOES-13       19 JAN 21019  20:45:00     0  -57 1-4,6                                                                    
  96  GOES-13       19 JAN 21019  20:15:00     0  -57 1-4,6                                                                    
  95  GOES-13       19 JAN 21019  19:45:00     0  -66 1-4,6                                                                    
  94  GOES-13       19 JAN 21019  19:15:00     0  -66 1-4,6                                                                    
  51  GOES-13       18 JAN 21018  20:45:00     0  -57 1-4,6                                                                    
  50  GOES-13       18 JAN 21018  20:15:00     0  -57 1-4,6                                                                    
  49  GOES-13       18 JAN 21018  19:45:00     0  -66 1-4,6                                                                    
  48  GOES-13       18 JAN 21018  19:15:00     0  -66 1-4,6

**Comment by nullpainter** [comment]
> That's one way to do it, but the offsets change every 12h, and from what I've seen it is a constant change.. Maybe it would be more reliable to just have the offset in px and time of the change in the config?

Yes and no, and I think my quick Github issue may have suggested that I was intending to calculate the _pixel offset_ based on these calculations. I'm actually just thinking of identifying whether to apply a left, or a right offset (based on a px constant).

To your point, if for a given timestamp we can be guaranteed that we know when the offset changes and in which direction and this never changes - sure, config all the way. But if there is any uncertainty, my approach should work.

**Comment by nullpainter** [comment]
Fixed in [v1.0.18](https://github.com/nullpainter/sanchez/releases/tag/v1.0.18).
