### ISSUE TITLE
Allow the -I interval argument to work independently of the -T argument

### ISSUE THREAD

**Issue by creinemann** [nullpainter/sanchez#75]
**Is your feature request related to a problem? Please describe.**
When running Sanchez without the -T timestamp argument to stitch two (or more images) setting the -I Interval argument does not change the default 30 minute tolerance

**Describe the solution you'd like**
All the -I argument to be used independently of -T argument
**Describe alternatives you've considered**
Some of the files I am trying to stitch are separated in time by 30, 40, or 60 minutes
![Screenshot 2021-03-05 070925](https://user-images.githubusercontent.com/47005123/110153372-94d69280-7da8-11eb-87e1-b4c9a3669066.jpg)

**Additional context**
Tried running Sanchez with a timestamp to match the time syntax as shown below.
`"F:/Sanchez/Sanchez.exe" reproject -s "F:\GOES1617TEMP\*.jpg" stitch -T %SanchezTime% -I 60 -S 0.6 -f -U -L -v  -a -r 2 -D "F:\Sanchez\Resources\static.json" -o "F:\GOES1617TEMP"`
which results in the string 
` F:\GOES1617TEMP\*.jpg stitch -T 2021-03-05T21:24:34 -I 60 -S 0.6 -f -U -L -v -a -r 2 -D F:\Sanchez\Resources\static.json -o F:\GOES1617TEMP`

Yet Sanchez does not process the images (I tried increasing interval to -I 120 as test.

log file:
[sanchez-20210305.log](https://github.com/nullpainter/sanchez/files/6093482/sanchez-20210305.log)

And I noticed this in the cache.db
`  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Filename TEXT NOT NULL,
  Longitude NUMERIC,
  Configuration TEXT NOT NULL
, Timestamp DATETIMEOFFSET)
indexCacheFilename_IXUnderlayCache
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Filename TEXT NOT NULL,
  Longitude NUMERIC,
  Configuration TEXT NOT NULL

CREATE TABLE [SchemaVersions] (
    SchemaVersionID INTEGER CONSTRAINT [PK_SchemaVersions_Id] PRIMARY KEY AUTOINCREMENT NOT NULL,
    ScriptName TEXT NOT NULL,
    Applied DATETIME NOT NULL`

**Comment by nullpainter** [comment]
Thanks Carl. It's a bit confusing, but that value is actually governed by `-d / --tolerance` ("Time tolerance in minutes in identifying suitable satellite images when combining")

**Comment by nullpainter** [comment]
I was just about to explain the difference between the two flags, but I can't quite remember. There is a nuance. Let me get back to you and maybe update the documentation / help text. If _I'm_ confused, it's not a good start!

**Comment by nullpainter** [comment]
Right. I think the word "stitching" in the `-I` option was throwing both of us off. This is the time interval between frames when performing a timelapse. Of course, this _can_ be aligned to `-d` but doesn't need to be.

For example, you could have a timelapse of 24 images with `-I` set to 60 minutes, but for each set of stitched images, you want ones that were captured with a tolerance of, say, 30 minutes.

**Comment by creinemann** [comment]
Added the -d argument to my script and all seems to work now, even with the variable -T %SanchezTime% -d 60
