### ISSUE TITLE
Update satellites.json to reflect change of naming convention for EWS-G1

### ISSUE THREAD

**Issue by creinemann** [nullpainter/sanchez#79]
Recently the file naming convention of EWS-G1 was changed from EWS-G1_4_20210807T174555Z.png to G13_4_20210807T174555Z.png  They are using the GVAR spec that NOAA uses. I changed the display name as shown.

```
    {
    "DisplayName": "EWS-G1-GOES13",
    "FilenamePrefix": "G13_[2-5]_",
    "FilenameParser": "Goesproc",
    "Invert": true,
    "Longitude": 61.5,
    "Brightness": 1.3,
    "Crop": [
      0.003166,
      0.089925,
      0.001166,
      0.001010
    ]
  },
  {
    "DisplayName": "EWS-G1-GOES13",
    "FilenamePrefix": "G13_1_",
    "FilenameParser": "Goesproc",
    "Invert": false,
    "Longitude": 61.5,
    "Brightness": 1.3,
    "Crop": [
      0.003166,
      0.089925,
      0.001166,
      0.001010
    ]
  },
```

**Comment by nullpainter** [comment]
Thanks @creinemann. I note your crop values are different to those in Sanchez - are these intentionally different, or just older?

**Comment by nullpainter** [comment]
(oops, ignore me - these were crop changes that I clearly just had never committed!)
