### ISSUE TITLE
sanchez version 1.0.20 incorrectly reports version number as sanchez-1.0.19

### ISSUE THREAD

**Issue by KiwiInNZ** [nullpainter/sanchez#83]
# Describe the bug
sanchez version 1.0.20 incorrectly reports version number as sanchez-1.0.19

# To Reproduce
Install sanchez from https://github.com/nullpainter/sanchez/releases/tag/v1.0.20 (I used the Linux version).

sanchez/Sanchez --version - to get the version number, which is reported as 1.0.19

## Expected behaviour
1.0.20 is reported, not 1.0.19

## Real behaviour
The correct version number is reported!

## Screenshots
Above should be clear enough/

## Environment:
Linux web 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64

## Additional information
I looked at the source code and I suspect the issue comes from Sanchez.csproj:

    <PropertyGroup>
        <Version>1.0.19</Version>
        <FileVersion>1.0.19</FileVersion>
    </PropertyGroup>

However I've not got an environment set up to build from the source code.

Minor isssue by far, but confused me when I thought I'd installed the new version, did a version check to see old version, so re-installed it, did version check to see the old version. I then stopped myself before I did an endless do...while version <> "1.0.19" loop...

**Comment by nullpainter** [comment]
Thanks Mike; I remembered to fix this in version 1.0.21 (coming shortly)
