### ISSUE TITLE
sanchez version 1.0.20 (and 1.0.19) fail to include GOES 18 image when doing a global combined IR image

### ISSUE THREAD

**Issue by KiwiInNZ** [nullpainter/sanchez#84]
# Describe the bug
sanchez version 1.0.20 (and 1.0.19) fail to include GOES 18 image when doing a global combined IR image with multiple satellites, despite having GOES 18 images which are picked up and appear in the verbose logging info

# To Reproduce
Download multiple weather satellites with IR image data (I can supply you a data set if required - just let me know a time / date combination and I can upload / host on my website).

Do a reprojection:
/home/pi/sanchez/Sanchez reproject -u /home/pi/wxcapture/process/config/world.200408.3x5400x2700.jpg -s /home/pi/goes/ -o /home/pi/wxcapture/process/2022-08-14-12-17-33V2.jpg -T 2022-08-14T12:17:33 -a -f -d 90 -D /home/pi/wxcapture/process/config/Satellites-IR.json -v > op2.txt

Examine the created image (see below) to find Pacific data is blank.

Note that the above Sanchez processing was working fine for many months with GOES 17 data, but is not working with GOES 18.

My Satellites-IR.json - uploaded as a .txt version as Github doesn't like me dragging a json file here...
[Satellites-IR.txt](https://github.com/nullpainter/sanchez/files/9335674/Satellites-IR.txt)

  {
    "DisplayName": "GOES-18",
    "FilenamePrefix": "GOES18_FD_CH13_(?!enhanced)",
    "FilenameParser": "Goesproc",
    "Longitude": -137.2,
    "Brightness": 0.95
  },

The underlay image is:
![world 200408 3x5400x2700](https://user-images.githubusercontent.com/51867737/184594343-0173da5a-7c66-433a-b2e1-5327afc349ab.jpg)

At the moment GOES 18 data is being broadcasted by GOES 17, with the position set to mimic what it should be if GOES 18 is positioned where GOES 17 are, so the GOES 18 data is the same as GOES 17 in the file.

## Expected behaviour
GOES 18 ch13 image is included into the combined image

## Real behaviour
GOES 18 ch13 image is included into the combined image

## Screenshots
Example image missing GOES 18 data
![2022-08-14-12-17-33V2](https://user-images.githubusercontent.com/51867737/184592526-cc983770-0460-40a8-b4e9-1c7eb6d80ca9.jpg)

## Environment:
Linux web 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64

## Additional information
Looking through the verbose output
[op2.txt](https://github.com/nullpainter/sanchez/files/9335658/op2.txt)

There are multiple satellites where there is a file handler which identifies matching files....

For GOES 18, it matches against CH 13 images, e.g. ones close in time to the requested time (2022-08-14T12:17:33) are:
[19:09:16 DBG] Matched GOES-18 handler for GOES18_FD_CH13_20220814T113020Z.jpg
[19:09:16 DBG] Matched GOES-18 handler for GOES18_FD_CH13_20220814T120020Z.jpg
[19:09:16 DBG] Matched GOES-18 handler for GOES18_FD_CH13_20220814T123020Z.jpg
[19:09:16 DBG] Matched GOES-18 handler for GOES18_FD_CH13_20220814T130020Z.jpg
[19:09:16 DBG] Matched GOES-18 handler for GOES18_FD_CH13_20220814T133020Z.jpg

So it looks like the Satellites-IR.json is valid.

And right at the end of the logfile, where it is doing the actual projections, it has clearly identified a GOES 18 image to use:
[19:09:21 INF] GOES-18 range 142.74 to -57.14 degrees
[19:09:21 INF] GOES-18 crop 222.80 to 253.80 degrees
[19:09:21 INF] GOES-18 latitude range 81.33 to -81.33 degrees
[19:09:21 INF] GOES-18 unwrapped longitude range 142.74 to 302.86 degrees
[19:09:21 INF] GOES-18 pixel range X: 4863 - 7275 px
[19:09:21 INF] GOES-18 pixel range Y: 131 - 2581 px
[19:09:21 INF] GOES-18 width: 2412 px
[19:09:21 INF] GOES-18 height: 2450 px
[19:09:21 INF] GOES-18 Reprojecting
[19:09:22 INF] GOES-18 range 142.74 to -57.14 degrees
[19:09:22 INF] GOES-18 crop 222.80 to 253.80 degrees
[19:09:22 INF] GOES-18 latitude range 81.33 to -81.33 degrees
[19:09:22 INF] GOES-18 unwrapped longitude range 142.74 to 302.86 degrees
[19:09:22 INF] GOES-18 pixel range X: 4863 - 7275 px
[19:09:22 INF] GOES-18 pixel range Y: 131 - 2581 px
[19:09:22 INF] GOES-18 width: 2412 px
[19:09:22 INF] GOES-18 height: 2450 px
[19:09:22 INF] GOES-18 Reprojecting

Note - it would be useful if the exact image file name / directory used was captured in the verbose output.

So based on the verbose output, it looks like GOES18 image data should be in the projection.

**Comment by nullpainter** [comment]
Curious. I don't have any GOES-18 images - renaming my test GOES-17 image to have a GOES-18 prefix and using your satellites file works as expected. A collection of sample files would be wonderful.

> Note - it would be useful if the exact image file name / directory used was captured in the verbose output.

Good idea!

**Comment by creinemann** [comment]
Interesting, I had a look through my images, and other than the missing EWS-G1 GOES-18 is showing in the reprojections as they should be.  Looking back further, from the 4 hour test window in June as well as the interleave starting August 1st, all appear as they should.

![Screenshot 2022-08-15 062456](https://user-images.githubusercontent.com/47005123/184627083-2d56f022-7799-468e-b94a-25914f42ce23.jpg)

**Comment by creinemann** [comment]
Running again under Sanchez V 1.0.21 - GOES-18 seems to  be showing up on the newest version too. 
![stitched-20220815T123000Z](https://user-images.githubusercontent.com/47005123/184664754-cac53099-09f6-4874-b54d-f32164643f4b.jpg)

**Comment by nullpainter** [comment]
@KiwiInNZ - version 1.0.21 hasn't been released yet, but it's in the `feature/performance` branch if you'd like to build it. I'd be interested to see if the problem manifests itself with the same source files.

Alternatively, there's a preview build here:

https://mega.nz/file/I1FjVbKY#gmhz9MpKGcpKcYvBdnMkXQi_wg4Mn6a9BGx8AuWEo_Y

This version hasn't changed anything that I can think of about satellite handling, and is mostly concerned with package upgrades and a rewrite of the haze/atmosphere feature.

**Comment by KiwiInNZ** [comment]
https://kiwiweather.com/downloads/IR-Sats.zip - try this as an updated set of test data with images for a whole UTC day (13/8/22) for:

- Electro L-2
- GK-2A
- GOES 16
- GOES 18
- Himawari 8

Let me know when you've got it as it is reasonably large, so I can delete it from my webserver.

And thanks to both @nullpainter and @creinemann for trying this out.

Will try the other stuff later, hopefully tonight...

**Comment by nullpainter** [comment]
Thanks Mike - I've got the file. Will test it out presently.

**Comment by nullpainter** [comment]
What timestamp were you using? The latest build from `master` and `feature/performance` (1.0.20 and 1.0.21 respectively) both seem to render GOES-18 correctly.

1.0.20:
![sanchez-1 0 20](https://user-images.githubusercontent.com/1732347/184713533-e88b90cb-1866-4abc-8c52-f590c0b2822c.jpg)

1.0.21:
![sanchez-1 0 21](https://user-images.githubusercontent.com/1732347/184713544-c90cf54c-5b95-40dc-a31b-aa4baf4ac585.jpg)

**Comment by creinemann** [comment]
I have the files, and ran it with the last three Sanchez versions and it
rendered as expected.

Carl

**Comment by nullpainter** [comment]
Do you owe me another beer, @KiwiInNZ? 😉

**Comment by creinemann** [comment]
![sanchezrendertest3](https://user-images.githubusercontent.com/47005123/184719934-37f11659-1b49-4d98-8803-c4f228942fcd.jpg)
forgot the image....

**Comment by KiwiInNZ** [comment]
> Do you owe me another beer, @KiwiInNZ? 😉

More than happy to buy you (and @creinemann) beers next time you're in Auckland (I've not been down in WLG for quite a while).

Need time to figure out why my code isn't working when it was fine with GOES 17 in the mix and the verbose output clearly showed it was including the GOES 18 image data, but the created images were obviously missing it.

**Comment by KiwiInNZ** [comment]
Doing some testing, taking the example which wasn't working, but using the exact same:

- IR-Sats.zip extracted
- Satellites-IR.json
- world.200408.3x5400x2700

Doing this for the latest Windows version, plus the previous Linux version works as expected.

Windows
w:
cd sanchez-1.0.21
W:\sanchez-1.0.21\Sanchez.exe reproject -u W:\world.200408.3x5400x2700.jpg -s W:\IR-Sats -o op-win-1.0.21.jpg -T 2022-08-13T12:00:00 -a -f -d 90 -D W:\Satellites-IR.json -v > op-win-1.0.21.txt

![op-win-1 0 21](https://user-images.githubusercontent.com/51867737/184828534-f750aa75-4244-491d-ab01-724ac7f2c019.jpg)
[op-win-1.0.21.txt](https://github.com/nullpainter/sanchez/files/9348865/op-win-1.0.21.txt)

Linux
/home/pi/sanchez/Sanchez reproject -u /home/pi/temp/world.200408.3x5400x2700.jpg -s /home/pi/temp/IR-Sats -o linux.1.0.20.jpg -T 2022-08-13T12:00:00 -a -f -d 90 -D /home/pi/temp/Satellites-IR.json -v > op-linux.1.0.20.txt
![linux 1 0 20](https://user-images.githubusercontent.com/51867737/184828593-5bee08db-98a2-4e13-bf79-0ca35aba6863.jpg)
[op-linux.1.0.20.txt](https://github.com/nullpainter/sanchez/files/9348869/op-linux.1.0.20.txt)

Now just need to figure out why my original isn't working and confused by the original verbose output saying that it was projecting a GOES 18 image but it not appearing in the image...

**Comment by KiwiInNZ** [comment]
Doing more tests, plus pulling a few of my remaining hairs, it is down to the source directory I'm using.

- Using the directory containing the image data for just a single day, that structure results in an image being created which contains the GOES 18 data
- Using the directory containing the image data for many days, that structure results in an image being created which does not contain the GOES 18 data

I'm wondering if this could be linked to the number of directories / files?

Could you do the enhancement that captures in the verbose output the location and filename for the image being used when it is doing the reprojection per satellite, e.g. adding the bolded line as below. This would confirm that the right file is being processed.

Are there any limits which could be linked to how many directories / files are being scanned?

**[19:09:21 INF] GOES-18 source image /home/pi/goes/goes18/fd/ch13/2022-08-13/GOES18_FD_CH13_20220813T053020Z.jpg**
[19:09:21 INF] GOES-18 range 142.74 to -57.14 degrees
[19:09:21 INF] GOES-18 crop 222.80 to 253.80 degrees
[19:09:21 INF] GOES-18 latitude range 81.33 to -81.33 degrees
[19:09:21 INF] GOES-18 unwrapped longitude range 142.74 to 302.86 degrees
[19:09:21 INF] GOES-18 pixel range X: 4863 - 7275 px
[19:09:21 INF] GOES-18 pixel range Y: 131 - 2581 px
[19:09:21 INF] GOES-18 width: 2412 px
[19:09:21 INF] GOES-18 height: 2450 px
[19:09:21 INF] GOES-18 Reprojecting
[19:09:22 INF] GOES-18 range 142.74 to -57.14 degrees
[19:09:22 INF] GOES-18 crop 222.80 to 253.80 degrees
[19:09:22 INF] GOES-18 latitude range 81.33 to -81.33 degrees
[19:09:22 INF] GOES-18 unwrapped longitude range 142.74 to 302.86 degrees
[19:09:22 INF] GOES-18 pixel range X: 4863 - 7275 px
[19:09:22 INF] GOES-18 pixel range Y: 131 - 2581 px
[19:09:22 INF] GOES-18 width: 2412 px
[19:09:22 INF] GOES-18 height: 2450 px
[19:09:22 INF] GOES-18 Reprojecting



Number of dates that my goes source directory has:
20220605  20220609  20220613  20220617  20220621  20220625  20220629  20220703  20220707  20220711  20220715  20220719  20220723  20220727  20220731  20220804  20220808  20220812  20220816
20220606  20220610  20220614  20220618  20220622  20220626  20220630  20220704  20220708  20220712  20220716  20220720  20220724  20220728  20220801  20220805  20220809  20220813
20220607  20220611  20220615  20220619  20220623  20220627  20220701  20220705  20220709  20220713  20220717  20220721  20220725  20220729  20220802  20220806  20220810  20220814
20220608  20220612  20220616  20220620  20220624  20220628  20220702  20220706  20220710  20220714  20220718  20220722  20220726  20220730  20220803  20220807  20220811  20220815

**Comment by KiwiInNZ** [comment]
There is just under 350GB of files in the /home/pi/goes/ directory, with 247,933 files in 6137 directories.

**Comment by nullpainter** [comment]
So greedy! That _shouldn't_ be a problem - I'm certainly not applying any artificial limits. I would ordinarily suggest it's an issue with the image matching code, but the fact that it claims to have found a GOES-18 image is perplexing. I'll add that logging tomorrow.

Do you have the .NET 6 SDK somewhere, or should I create a build for you?

**Comment by nullpainter** [comment]
I've just added the requested logging to the `feature/performance` branch. Let me know if you manage to narrow down the issue.

If the target files _do_ look sane, do work in isolation and if it is looking related to the 250k files, perhaps you could send me the output of a `find /home/pi/goes` and I can use this to create that many empty files.

Or I could just look at the code...

PS. The branch was named because I thought, as part of library upgrades, I had a performance boost. Turns out that it performs just the same as before. Boo.

**Comment by KiwiInNZ** [comment]
I've not got the .NET SDK (never used it, so far...).

However I can always point the v1.0.20 code at my backup drive (8TB, ~3TB used) of sat images. That should validate performance!

**Comment by nullpainter** [comment]
Now's an excellent time to start! This evening, I'll create a new preview build and which includes this logging and send it through to you.

**Comment by KiwiInNZ** [comment]
Output from `find /home/pi/goes`:
[files.zip](https://github.com/nullpainter/sanchez/files/9356789/files.zip)

Since the selection of a files for a day, which works, was fetched from the location where it doesn't work, I'd say the files are probably "sane", although not having anything to test sanity for files, I even tried `sane-find-scanner` to no avail!

If you're looking at the content of the ~/goes directory, most directories should be fairly obvious, other than:
* sanchez - where I put sanchez processed images (with a folder per satellite)
* web - where I put images where I've added image info
And yes, I tried removing these from the ~/goes directory just in case they were the problem, but no change.

**Comment by nullpainter** [comment]
Thanks Mike. [Here's a build](https://mega.nz/file/chMxiKqJ#a3drT_DtwSrz23au9jwEvenPxF07gH144f1RGLODgEc) with the additional logging.

**Comment by KiwiInNZ** [comment]
Minor problem - Sanchez.exe doesn't work too well on Linux (Linux web 5.10.0-15-amd64 https://github.com/nullpainter/sanchez/pull/1 SMP Debian 5.10.120-1 (2022-06-09) x86_64).

Can you do a build for a "proper" OS? ;)

**Comment by nullpainter** [comment]
Oh, oops! [Try this](https://mega.nz/file/U59GWapb#ivzGn1L1iFtvz_UaNRduVdZh9OcZJy8Yg7RUoP8bhZc) on for size.

**Comment by KiwiInNZ** [comment]
![image](https://user-images.githubusercontent.com/51867737/185078744-b499a443-487a-440d-9eaa-2514ea41d8d8.png)
Most unusual, didn't have the execute attribute set.

Then when trying to run:
[op-v6.txt](https://github.com/nullpainter/sanchez/files/9358069/op-v6.txt)

**Comment by nullpainter** [comment]
Oh, my apologies. The .NET 6 single file packaging can be a little temperamental. Apologies, and thank you for your patience - will create another build presently.

(It doesn't have the executable attribute set because I'm building it on Windows, which has no notion of such things. The official releases are created by Github in a container)

**Comment by nullpainter** [comment]
Again untested, but [this](https://mega.nz/file/wgFF2ByQ#JoWN59Clsl5ldQerLJjqWvZdlKXEIfVnO9AfZ0ABgmk) should work less bad.

**Comment by KiwiInNZ** [comment]
Drum roll....
![v6](https://user-images.githubusercontent.com/51867737/185092452-df33c3a3-e0b5-401d-956a-9c1ee2ff61fc.jpg)
And the verbose output...
[op-v6.txt](https://github.com/nullpainter/sanchez/files/9358606/op-v6.txt)

Interesting, reprojecting two GOES 18 images!
```
[22:01:10 INF] GOES-18 source image /home/pi/goes/goes18/fd/ch13/2022-08-13/GOES18_FD_CH13_20220813T120021Z.jpg
[22:01:10 INF] GOES-18 range 142.74 to -57.14 degrees
[22:01:10 INF] GOES-18 crop 222.80 to 253.80 degrees
[22:01:10 INF] GOES-18 latitude range 81.33 to -81.33 degrees
[22:01:10 INF] GOES-18 unwrapped longitude range 142.74 to 302.86 degrees
[22:01:10 INF] GOES-18 pixel range X: 4863 - 7275 px
[22:01:10 INF] GOES-18 pixel range Y: 131 - 2581 px
[22:01:10 INF] GOES-18 width: 2412 px
[22:01:10 INF] GOES-18 height: 2450 px
[22:01:10 INF] GOES-18 Reprojecting
[22:01:11 INF] GOES-18 source image /home/pi/goes/goes18/fd/fc/2022-08-13/GOES18_FD_FC_20220813T120021Z.jpg
[22:01:11 INF] GOES-18 range 142.74 to -57.14 degrees
[22:01:11 INF] GOES-18 crop 222.80 to 253.80 degrees
[22:01:11 INF] GOES-18 latitude range 81.33 to -81.33 degrees
[22:01:11 INF] GOES-18 unwrapped longitude range 142.74 to 302.86 degrees
[22:01:11 INF] GOES-18 pixel range X: 4863 - 7275 px
[22:01:11 INF] GOES-18 pixel range Y: 131 - 2581 px
[22:01:11 INF] GOES-18 width: 2412 px
[22:01:11 INF] GOES-18 height: 2450 px
[22:01:11 INF] GOES-18 Reprojecting

```
And the two images it used are:
![GOES18_FD_FC_20220813T120021Z](https://user-images.githubusercontent.com/51867737/185092979-ba9651f5-4647-483f-9f1a-ed748b6c48a6.jpg)
![GOES18_FD_CH13_20220813T120021Z](https://user-images.githubusercontent.com/51867737/185092988-3863c036-826f-451f-beb5-821fd4377149.jpg)

**Comment by KiwiInNZ** [comment]
When I shared the zip file with the satellite images, I only included the ch13 images, not any other. This might be a factor...

**Comment by nullpainter** [comment]
Bingo! It's not that it's not rendering it - it will be choosing the full colour, mostly night image.

You may wish to have a separate JSON file for stitching which only includes CH13. You can provide the path on the command-line.

Alternatively, the source directory argument supports globbing.

**Comment by KiwiInNZ** [comment]
OK, have figured out what is happening....
![v7](https://user-images.githubusercontent.com/51867737/185095336-7a02f38d-ac34-4771-b335-7825ded59f54.jpg)

If you look in my json file (uploaded right at the top), there are two entries for GOES 18, one for IR and one for FC, since I reproject both and somehow by projecting both it cancels out the two.
```
  {
    "DisplayName": "GOES-18",
    "FilenamePrefix": "GOES18_FD_CH13_(?!enhanced)",
    "FilenameParser": "Goesproc",
    "Longitude": -137.2,
    "Brightness": 0.95
  },
  {
    "DisplayName": "GOES-18",
    "FilenamePrefix": "GOES18_FD_FC_(?!enhanced)",
    "FilenameParser": "Goesproc",
    "Longitude": -137.2,
    "Brightness": 0.95
  },
```

**Comment by nullpainter** [comment]
Snap!

**Comment by KiwiInNZ** [comment]
Not just the night ones, it is doing it for all:
![image](https://user-images.githubusercontent.com/51867737/185095999-993e2bf4-d43b-4ab4-8f04-e11dc297e832.png)

Looks like I just need to change it to have two json files, one for when I want to use IR channels and one for FC channels.

Having that extra logging made all the difference, so can I turn this into an enhancement request with this as proof for the value of having it?

**Comment by nullpainter** [comment]
Oh, it's already in there! No persuasion required. You can rarely have enough logs. I appreciate the suggestion.

**Comment by nullpainter** [comment]
Not that it will necessarily help you in this situation, but I may also see if I can get Sanchez to behave less wrong (logging a warning if duplicates, picking the first)

**Comment by KiwiInNZ** [comment]
Ok, I've now two JSON files and the IR / FC one is used as appropriate.
![2022-08-17-10-46-46_web](https://user-images.githubusercontent.com/51867737/185101147-d91edb4b-ef00-4a3e-a204-e9658a01fb6a.jpg)
And all the way through to the webserver - https://kiwiweather.com/index.php/other-geostationary/global-combined/

Totally agree about the value of logging, especially anywhere complex, just watching you don't kill performance by logging too much!

Warning of duplicates would be good to see.

**Comment by KiwiInNZ** [comment]
Think this one can be closed now, unless you want to close it out with the updated logging / warning?

Thank you for helping solve an intriguing problem.

**Comment by nullpainter** [comment]
Great, thanks Mike. I've been able to reproduce your issue. In my image matching code for stitching, I was already selecting the first matching image which met the time criteria, but I was doing it by satellite definition only:

```c#
// Return the closest match per satellite
var matched = GetMatchedFiles(registrations, targetTimestamp);
return matched
    .GroupBy(m => m.Registration.Definition)
    .Select(entry => entry
        .OrderBy(e => e.Deviation)
        .First()
        .Registration)
    .ToList();
```

To prevent odd images from being rendered when there are multiple definitions in the same file with the same longitude, I've restricted this to select distinct images by longitude:

```c#
// Return the closest match per satellite
var matched = GetMatchedFiles(registrations, targetTimestamp);
return matched
    .GroupBy(m => m.Registration.Definition)
    .DistinctBy(entry => entry.Key.Longitude)
    .Select(entry => entry
        .OrderBy(e => e.Deviation)
        .First()
        .Registration)
    .ToList();
```
