### ISSUE TITLE
Underlay cache does not keep transparency

### ISSUE THREAD

**Issue by thomasdouwes** [nullpainter/sanchez#94]
# Describe the bug

When producing an image with a transparent underlay, the first run will work, but the second run will produce an image with black instead of transparency.

# To Reproduce

Create an image with a PNG containing transparency as the underlay.
Run a second time and the output will have black instead of transparency.

## Expected behaviour

An image with transparency is produced every run.

## Real behaviour

The second run with the same underlay produces an image with a black in place of transparency.

## Screenshots

None needed.

## Environment:

OS: Arch linux (rolling) 
Kernel: 6.2.7
Architecture: x86_64

## Additional information

I think it is the underlay cache because on the first run i see "Caching underlay" but on the rest I see "Using cached underlay"

Also, using touch to update the modification time of the file to make sanchez refresh the cache also makes the output image have transparency.

**Comment by nullpainter** [comment]
Thanks for reporting this! I suspect it's because I'm storing the underlay as a JPEG. A simple fix would be to use a PNG instead.

**Comment by nullpainter** [comment]
Fixed in [v1.0.24](https://github.com/nullpainter/sanchez/releases/tag/v1.0.24). I also saw fit to upgrade to .NET 7, so hopefully this doesn't cause any headaches.

**Comment by thomasdouwes** [comment]
Thank you for the fast fix, I tested it and transparent underlays are working now.
