### ISSUE TITLE
Running on Orange Pi

### ISSUE THREAD

**Issue by hasaranga** [nullpainter/sanchez#98]
Hi,

When I tried to run Sanchez ARM build (release page) on Orange Pi, I got error saying: 

-bash: ./Sanchez: cannot execute: required file not found

Why is that? Are there any dependencies which I should install?

**Comment by nullpainter** [comment]
Without additional information, I'm not entirely sure - I'm rather at the mercy of dotnet to generate a valid ARM build that runs on all common Linux platforms. I know that others are using Sanchez on Rasberry PIs. I don't have an Orange Pi to test with, but I _do_ have a Banana Pi (so many fruit!) so will test it in the weekend.

**Comment by nullpainter** [comment]
Are you able to tell me the exact model number? I will do some digging. Although, if it doesn't work I fear the answer may not be great. Quick Googling suggests that dotnet _does_ work on some Orange Pis.

**Comment by hasaranga** [comment]
I was running it on Orange Pi Zero2W

**Comment by hasaranga** [comment]
OK, I was able to recompile the project for orange pi zero 2W.

`
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --channel 7.0

sudo apt install libc6
sudo apt install libgcc-s1
sudo apt install libgssapi-krb5-2
sudo apt install libicu63 (for debian 10.x)
sudo apt install libicu67 (for debian 11.x)
sudo apt install libicu72 (for debian 12.x)
sudo apt install libssl1.1
sudo apt install libstdc++6
sudo apt install zlib1g

export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

git clone --depth=1 https://github.com/nullpainter/sanchez.git
cd sanchez
dotnet run --project Sanchez
dotnet publish  Sanchez/Sanchez.csproj -p:PublishSingleFile=true -r linux-arm64 -c Release -o output
`
using flag "-p:PublishTrimmed=true" causes exception when running the program. So I removed it.
now the program is available in the output folder.

**Comment by nullpainter** [comment]
Oh excellent work. I remember that trimming used to be a bit problematic, but I hoped that .NET 7 (and now 8) had sorted out all the wrinkles. Does everything now work for you?

**Comment by hasaranga** [comment]
Yes. Everything works without any issues. I think you should put build instructions on the readme page.

**Comment by ZL1LAC** [comment]
New version fyi now needs.
./dotnet-install.sh --channel 9.0
